version: '3'

services:
  jambo.auth.webapi:
    image: ivanpaulovich/jambo:auth.webapi
    build:
      context: ./Jambo.Auth.WebAPI
      dockerfile: Dockerfile
    ports:
        - 7070:80
  jambo.producer.webapi:
    image: ivanpaulovich/jambo:producer.webapi
    build:
      context: ./Jambo.Producer.WebAPI
      dockerfile: Dockerfile
    links:
      - "mongodb:mongo"
    depends_on:
      - mongodb
      - kafka
    environment:
      - ASPNETCORE_URLS=http://*:80
    ports:
        - 7080:80
  jambo.consumer.console:
    image: ivanpaulovich/jambo:consumer.console
    build:
      context: ./Jambo.Consumer.Console
      dockerfile: Dockerfile
    links:
      - "mongodb:mongo"
    depends_on:
      - mongodb
      - kafka
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
        - 27017:27017
  kafka:
    image: landoop/fast-data-dev:latest
    ports:
        - 2181:2181
        - 3030:3030
        - 8081-8083:8081-8083
        - 9581-9585:9581-9585
        - 9092:9092
    environment:
      - ADV_HOST=10.0.75.1
