version: '3'

services:
  jambo.web:
    image: jambo.web
    build:
      context: ./Jambo.Web
      dockerfile: Dockerfile
    links:
      - "mongodb:mongo"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_URLS=http://*:80
  jambo.consumer:
    image: jambo.consumer
    build:
      context: ./Jambo.Consumer
      dockerfile: Dockerfile
    links:
      - "mongodb:mongo"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
        - 27017:27017
  kafka:
    image: landoop/fast-data-dev:latest
    ports:
        - 2181:2181
        - 3030:3030
        - 8081-8083:8081-8083
        - 9581-9585:9581-9585
        - 9092:9092
    environment:
      - ADV_HOST=10.0.75.1