version: '4'

services:
  ci-build:
    image: microsoft/aspnetcore-build:latest
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Jambo.sln && dotnet publish ./Jambo.sln -c Release -o ./obj/Docker/publish"
