version: '3'

services:
  jambo.auth.webapi:
    image: ivanpaulovich/jambo:auth.webapi
    build:
      context: ./Jambo.Auth.WebAPI
      dockerfile: Dockerfile
  jambo.producer.webapi:
    image: ivanpaulovich/jambo:producer.webapi
    build:
      context: ./Jambo.Producer.WebAPI
      dockerfile: Dockerfile
    links:
      - "mongodb:mongo"
    depends_on:
      - mongodb
      - kafka
    environment:
      - ASPNETCORE_URLS=http://*:80
      - ServiceBus__ConnectionString=kafka:9092
      - ServiceBus__Topic=jambov32
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__Database=jambov32
  jambo.consumer.console:
    image: ivanpaulovich/jambo:consumer.console
    build:
      context: ./Jambo.Consumer.Console
      dockerfile: Dockerfile
    links:
      - "mongodb:mongo"
    depends_on:
      - mongodb
      - kafka
    environment:
      - ASPNETCORE_URLS=http://*:80
      - ServiceBus__ConnectionString=kafka:9092
      - ServiceBus__Topic=jambov32
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__Database=jambov32
  mongodb:
    image: mongo
    ports:
        - 27017
  kafka:
    image: landoop/fast-data-dev:latest
    ports:
        - 2181
        - 3030
        - 8081-8083
        - 9581-9585
        - 9092
    environment:
      - ADV_HOST=kafka
